### ISSUE TITLE
No Thumbnails

### ISSUE THREAD

**Issue by jr-sw** [darktrojan/newtabtools#130] opened 2015-09-28 08:27 UTC
I get no thumbnails displayed now. Latest New Tab download. Firefox 41.0 Win XP Pro SP3. I used to get them bit now all empty.. Using Refresh thumbnail Option does not recover thumbnail either. Am I missing something?

**Comment by darktrojan** [comment] 2015-10-07 09:05
Do you have NoScript? It disables thumbnail creation by default. It's probably not the only extension that does so, but it's the only one I know of.

**Comment by jr-sw** [comment] 2015-10-07 11:20
No NoScript. Thumbnails were working with older versions of Newtabtools/Firefox. I have recently tried a couple of other speed dial tools and they generate thumbnails correctly (now on Firefox 41.0.1)

**Comment by indivisible-irl** [comment] 2015-10-07 14:22
Chiming in that I'm experiencing the same bug with NTT 53 and FF 41.0.1 on OSX (mavericks).
I do have adblock edge installed but it's never interfered with NTT before (that I'm aware of) and no other greasemonkey, noscript type addons.

**Comment by Joffrey-Parisot** [comment] 2015-10-22 10:46
I can't upload my own picture or use a link to customize a thumbnail (but the Refresh is ok). I'm on Firefox Dev 43.0a2, Windows 7, and all my addons are disabled.

**Comment by darktrojan** [comment] 2015-10-22 10:57
@Joffrey-Parisot I've just had a look and figured out what's causing the bug you see. It's caused by a change in Firefox 43 so it's a different bug from what the others are seeing.

**Comment by Joffrey-Parisot** [comment] 2015-10-22 12:12
@darktrojan Thx for your response. Is it necessary to open an issue about my problem, or is it OK for you ?

**Comment by darktrojan** [comment] 2015-10-22 23:53
@Joffrey-Parisot, no that's okay, I've made a fix already, which will be in the next version. Thanks.

**Comment by Micha-Btz** [comment] 2015-12-13 18:55
@darktrojan i have no script and i won't to disable it. how can i get thumbnails anyway?

**Comment by darktrojan** [comment] 2015-12-14 01:51
@Micha-Btz I have the prefs `noscript.bgThumbs.allowed` set to `true` and `noscript.bgThumbs.disableJS` to `false`. I think only the first is necessary.

**Comment by Micha-Btz** [comment] 2015-12-15 20:42
@darktrojan works, thanks

**Closed** 2017-09-15 00:09 UTC
